language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
notifications:
  email: false
addons:
  apt:
    packages:
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
install: sudo apt-get install cmake libXxf86vm-dev libxinerama-dev libxcursor-dev
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); using GLVisualize'
